# Generated by Django 3.2 on 2024-01-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_reg_date',
            field=models.DateTimeField(null=True),
        ),
    ]
