# Generated by Django 3.2 on 2024-01-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_profile_business_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_age',
            field=models.IntegerField(null=True),
        ),
    ]
